# Generated by Django 4.2 on 2024-01-03 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('actividades_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Actividades')),
                ('nombre_de_actividad', models.CharField(max_length=200, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('tiempo_requerido', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cosechas',
            fields=[
                ('cosecha_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Cosechas')),
                ('nombre_de_cosecha', models.CharField(max_length=200, null=True)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('empleado_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Empleado')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('apellido', models.CharField(max_length=100, null=True)),
                ('paga', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lluvias',
            fields=[
                ('lluvias_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Lluvias')),
                ('fecha', models.DateField(null=True)),
                ('lectura_de_lluvia', models.FloatField(null=True)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Predios',
            fields=[
                ('predio_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Predios')),
                ('nombre_de_predio', models.CharField(max_length=200, null=True)),
                ('tipo_de_suelo', models.CharField(max_length=200, null=True)),
                ('tamaño_de_predio', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Productos')),
                ('nombre_de_producto', models.CharField(max_length=200, null=True)),
                ('tipo_de_producto', models.CharField(max_length=200, null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_de_Actividad',
            fields=[
                ('tipo_act_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Theme')),
                ('tipo_de_actividad', models.CharField(max_length=200, null=True)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('tareas_id', models.AutoField(primary_key=True, serialize=False, verbose_name='tareas')),
                ('tiempo_de_actividad', models.IntegerField(null=True)),
                ('notas', models.TextField(null=True)),
                ('fecha_planificada', models.DateField(null=True)),
                ('fecha_completada', models.DateField(blank=True, null=True)),
                ('planned', models.BooleanField(null=True)),
                ('numero_de_injertos', models.IntegerField(null=True)),
                ('cantidad_agua_galones', models.IntegerField(null=True)),
                ('cantidad_agua_tiempo', models.IntegerField(null=True)),
                ('cantidad_siembra', models.IntegerField(null=True)),
                ('unidades_siembra', models.CharField(max_length=50, null=True)),
                ('cantidad_cosecha_unidades', models.IntegerField(null=True)),
                ('cantidad_cosecha_lbs', models.IntegerField(null=True)),
                ('cantidad_utilizada', models.IntegerField(null=True)),
                ('unidades_fertilizacion', models.CharField(max_length=100, null=True)),
                ('id_agroptima', models.IntegerField(null=True)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.empleados')),
                ('nombre_de_actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividad_nombre', to='tareas.actividades')),
                ('nombre_de_cosecha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.cosechas')),
                ('predio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.predios')),
                ('producto_utilizado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_utilizado', to='tareas.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('receta_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Recetas')),
                ('receta_nombre', models.TextField(null=True)),
                ('descripcion', models.TextField(null=True)),
                ('cadence', models.IntegerField(null=True)),
                ('dias', models.IntegerField(null=True)),
                ('actividades_a_crear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_a_crear', to='tareas.actividades')),
                ('cosecha_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.cosechas')),
                ('trigger_actividad_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_actividad', to='tareas.actividades')),
            ],
        ),
        migrations.AddField(
            model_name='actividades',
            name='tipo_de_actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.tipo_de_actividad'),
        ),
    ]
