# Generated by Django 3.2 on 2024-06-14 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('actividades_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Actividades')),
                ('nombre_de_actividad', models.CharField(max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tiempo_requerido', models.IntegerField(null=True)),
                ('tipo_producto_asociado', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cosechas',
            fields=[
                ('cosecha_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Cosechas')),
                ('nombre_de_cosecha', models.CharField(max_length=200, null=True)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('empleado_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Empleado')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('apellido', models.CharField(max_length=100, null=True)),
                ('paga', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indice_Calor',
            fields=[
                ('indice_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Indice')),
                ('fecha', models.DateField(null=True)),
                ('lectura_de_temperatura', models.FloatField(null=True)),
                ('lectura_de_humedad', models.FloatField(null=True)),
                ('indice_de_calor', models.FloatField(null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lluvias',
            fields=[
                ('lluvias_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Lluvias')),
                ('fecha', models.DateField(null=True)),
                ('lectura_de_lluvia', models.FloatField(null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Predios',
            fields=[
                ('predio_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Predios')),
                ('nombre_de_predio', models.CharField(max_length=200, null=True)),
                ('tipo_de_suelo', models.CharField(max_length=200, null=True)),
                ('tamaño_de_predio', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Productos')),
                ('nombre_de_producto', models.CharField(max_length=200, null=True)),
                ('tipo_de_producto', models.CharField(max_length=200, null=True, unique=True)),
                ('plaguicida_check', models.BooleanField(null=True)),
                ('abonamiento_check', models.BooleanField(null=True)),
                ('tipo_de_plaguicida', models.CharField(max_length=200, null=True)),
                ('tipo_de_abonamiento', models.CharField(max_length=200, null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_de_Actividad',
            fields=[
                ('tipo_act_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Theme')),
                ('tipo_de_actividad', models.CharField(max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('tareas_id', models.AutoField(primary_key=True, serialize=False, verbose_name='tareas')),
                ('tiempo_de_actividad', models.IntegerField(null=True)),
                ('notas', models.TextField(null=True)),
                ('fecha_planificada', models.DateField(null=True)),
                ('fecha_completada', models.DateField(blank=True, null=True)),
                ('planned', models.BooleanField(null=True)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.empleados')),
                ('nombre_de_actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividad_nombre', to='tareas.actividades')),
                ('nombre_de_cosecha', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.cosechas')),
                ('predio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.predios')),
                ('producto_asociado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('receta_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Recetas')),
                ('receta_nombre', models.TextField(null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cadence', models.IntegerField(null=True)),
                ('dias', models.IntegerField(null=True)),
                ('actividades_a_crear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_a_crear', to='tareas.actividades')),
                ('cosecha_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.cosechas')),
                ('trigger_actividad_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_actividad', to='tareas.actividades')),
            ],
        ),
        migrations.CreateModel(
            name='InfoPorActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=50)),
                ('tipo_de_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.tipo_de_actividad')),
            ],
        ),
        migrations.CreateModel(
            name='doc_repo',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Documento')),
                ('nombre_documento', models.CharField(max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url_documento', models.URLField()),
                ('cosecha_asociada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.cosechas')),
                ('producto_asociado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Data_Por_Tarea',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Datos_Tarea')),
                ('value', models.TextField()),
                ('info_por_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.infoporactividad')),
                ('tarea_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.tareas')),
            ],
        ),
        migrations.AddField(
            model_name='actividades',
            name='tipo_de_actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.tipo_de_actividad'),
        ),
    ]
