# Generated by Django 5.0 on 2023-12-25 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_actividad', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tiempo_requerido', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cosechas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_cosecha', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('paga', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lluvias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('lectura_de_lluvia', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Predios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_predio', models.CharField(max_length=200)),
                ('tipo_de_suelo', models.CharField(max_length=200)),
                ('tamaño_de_predio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_producto', models.CharField(max_length=200)),
                ('tipo_de_producto', models.CharField(max_length=200)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('cadence', models.IntegerField()),
                ('dias', models.IntegerField()),
                ('actividades_a_crear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_a_crear', to='tareas.actividades')),
                ('cosecha_asociada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.cosechas')),
                ('trigger_actividad_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_actividad', to='tareas.actividades')),
            ],
        ),
        migrations.CreateModel(
            name='Tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_de_actividad', models.IntegerField()),
                ('notas', models.TextField()),
                ('fecha_planificada', models.DateField()),
                ('fecha_completada', models.DateField(blank=True, null=True)),
                ('planned', models.BooleanField()),
                ('numero_de_injertos', models.IntegerField()),
                ('cantidad_agua_galones', models.IntegerField()),
                ('cantidad_agua_tiempo', models.IntegerField()),
                ('cantidad_siembra', models.IntegerField()),
                ('unidades_siembra', models.CharField(max_length=50)),
                ('cantidad_cosecha_unidades', models.IntegerField()),
                ('cantidad_cosecha_lbs', models.IntegerField()),
                ('cantidad_utilizada', models.IntegerField()),
                ('unidades_fertilizacion', models.CharField(max_length=100)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.empleados')),
                ('nombre_de_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividad_nombre', to='tareas.actividades')),
                ('nombre_de_cosecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.cosechas')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.predios')),
                ('producto_semilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_semilla', to='tareas.productos')),
                ('producto_utilizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_utilizado', to='tareas.productos')),
            ],
        ),
    ]
