# Generated by Django 5.0 on 2023-12-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividades',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cosechas',
            name='id',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lluvias',
            name='id',
        ),
        migrations.RemoveField(
            model_name='predios',
            name='id',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='id',
        ),
        migrations.RemoveField(
            model_name='recetas',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='id',
        ),
        migrations.AddField(
            model_name='actividades',
            name='actividades_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Actividades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cosechas',
            name='cosecha_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Cosechas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleados',
            name='empleado_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Empleado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lluvias',
            name='lluvias_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Lluvias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predios',
            name='predio_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Predios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productos',
            name='producto_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Productos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recetas',
            name='receta_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Recetas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tareas',
            name='tareas_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='tareas'),
            preserve_default=False,
        ),
    ]
