# Generated by Django 4.2 on 2024-03-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tareas',
            old_name='cantidad_utilizada',
            new_name='cantidad_producto',
        ),
        migrations.AddField(
            model_name='tareas',
            name='cantidad_agua_plaguicida_utilizada',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tareas',
            name='razon_de_utilizar_producto',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lluvias',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='cantidad_agua_galones',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipo_de_actividad',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
