# Generated by Django 5.0 on 2023-12-26 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_remove_actividades_id_remove_cosechas_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Themes_Actividades',
            fields=[
                ('theme_act_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Productos')),
                ('tipo_de_actividad', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('nombre_de_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_nombre', to='tareas.actividades')),
            ],
        ),
    ]
