# Generated by Django 4.2 on 2024-03-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_rename_cantidad_utilizada_tareas_cantidad_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='origen_agua',
            field=models.TextField(null=True),
        ),
    ]
