# Generated by Django 4.2 on 2024-03-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_tareas_origen_agua'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='tipo_de_abono',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='origen_agua',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='razon_de_utilizar_producto',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
