# Generated by Django 5.0 on 2023-12-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_themes_actividades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='nombre_de_actividad',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='tiempo_requerido',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cosechas',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cosechas',
            name='nombre_de_cosecha',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='apellido',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='paga',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lluvias',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lluvias',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='lluvias',
            name='lectura_de_lluvia',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='predios',
            name='nombre_de_predio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='predios',
            name='tamaño_de_predio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='predios',
            name='tipo_de_suelo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre_de_producto',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='tipo_de_producto',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='cadence',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recetas',
            name='dias',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='cantidad_agua_galones',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='cantidad_agua_tiempo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='cantidad_cosecha_lbs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='cantidad_cosecha_unidades',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='cantidad_siembra',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='cantidad_utilizada',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='fecha_planificada',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='notas',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='numero_de_injertos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='planned',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='tiempo_de_actividad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='unidades_fertilizacion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='themes_actividades',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='themes_actividades',
            name='tipo_de_actividad',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
