# Generated by Django 4.2 on 2024-03-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_tareas_tipo_de_abono_alter_tareas_origen_agua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='abonamiento_check',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='plaguicida_check',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='tipo_de_abonamiento',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='tipo_de_plaguicida',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
