# Generated by Django 5.0 on 2023-12-26 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_alter_actividades_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareas',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.empleados'),
        ),
    ]
