# Generated by Django 4.2 on 2024-03-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_productos_abonamiento_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='cantidad_final',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tareas',
            name='cantidad_principal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tareas',
            name='procedencia_de_semilla',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tareas',
            name='tipo_de_semilla',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
