# Generated by Django 4.2 on 2024-03-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_tareas_cantidad_final_tareas_cantidad_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='tipo_de_plaguicida',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
