# Generated by Django 5.0 on 2023-12-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_alter_tareas_nombre_de_actividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lluvias',
            name='lectura_de_lluvia',
            field=models.FloatField(null=True),
        ),
    ]
