# Generated by Django 5.0 on 2023-12-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0007_alter_lluvias_lectura_de_lluvia'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas',
            name='receta_nombre',
            field=models.TextField(null=True),
        ),
    ]
