# Generated by Django 4.2 on 2024-03-17 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0007_tareas_tipo_de_plaguicida'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc_repo',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Theme')),
                ('nombre_documento', models.CharField(max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url_documento', models.URLField()),
                ('cosecha_asociada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.cosechas')),
                ('producto_asociado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.productos')),
            ],
        ),
    ]
