# Generated by Django 5.0 on 2023-12-27 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0008_recetas_receta_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_Actividades',
            fields=[
                ('theme_act_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Theme')),
                ('tipo_de_actividad', models.CharField(max_length=200, null=True)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='actividades',
            name='tipo_de_actividad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Themes_Actividades', to='tareas.tipo_actividades'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Themes_Actividades',
        ),
    ]
