# Generated by Django 4.2 on 2024-04-22 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0009_indice_calor'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPorActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=50)),
                ('tipo_de_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.tipo_de_actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Data_Por_Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('info_por_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.infoporactividad')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.tareas')),
            ],
        ),
    ]
