# Generated by Django 5.0 on 2023-12-27 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0009_tipo_actividades_actividades_tipo_de_actividad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividades',
            name='tipo_de_actividad',
        ),
        migrations.CreateModel(
            name='Themes_Actividades',
            fields=[
                ('theme_act_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Theme')),
                ('tipo_de_actividad', models.CharField(max_length=200, null=True)),
                ('descripcion', models.TextField(null=True)),
                ('nombre_de_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_nombre', to='tareas.actividades')),
            ],
        ),
        migrations.DeleteModel(
            name='tipo_Actividades',
        ),
    ]
