# Generated by Django 4.2 on 2024-05-08 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0010_infoporactividad_data_por_tarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='cantidad_agua_galones',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='cantidad_agua_plaguicida_utilizada',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='cantidad_agua_tiempo',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='cantidad_cosecha_lbs',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='cantidad_cosecha_unidades',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='cantidad_final',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='cantidad_principal',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='cantidad_producto',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='cantidad_siembra',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='id_agroptima',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='numero_de_injertos',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='origen_agua',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='procedencia_de_semilla',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='producto_utilizado',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='razon_de_utilizar_producto',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='tipo_de_abono',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='tipo_de_plaguicida',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='tipo_de_semilla',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='unidades_fertilizacion',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='unidades_siembra',
        ),
    ]
