# Generated by Django 4.2 on 2024-05-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0011_remove_tareas_cantidad_agua_galones_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_por_tarea',
            old_name='tarea',
            new_name='tarea_asociada',
        ),
        migrations.RemoveField(
            model_name='data_por_tarea',
            name='id',
        ),
        migrations.AddField(
            model_name='data_por_tarea',
            name='data_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='Datos_Tarea'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doc_repo',
            name='document_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='indice_calor',
            name='indice_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Indice'),
        ),
    ]
