# Generated by Django 5.0 on 2023-12-27 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0011_tipo_de_actividad_actividades_tipo_de_actividad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_de_actividad',
            old_name='theme_act_id',
            new_name='tipo_act_id',
        ),
    ]
