# Generated by Django 4.2 on 2024-05-10 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0012_rename_tarea_data_por_tarea_tarea_asociada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='producto_asociado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.productos'),
        ),
    ]
