# Generated by Django 4.2 on 2024-05-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0015_tareas_producto_asociado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='tipo_producto_asociado',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='tipo_de_producto',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
